FROM node:20-alpine
WORKDIR /app

COPY stellar-payment-platform/package*.json ./

ENV PRISMA_SKIP_POSTINSTALL_GENERATE="true"

RUN npm ci 

COPY stellar-payment-platform/ .
RUN npx prisma generate
EXPOSE 5000
CMD ["node", "server.js"]