FROM node:20-alpine
WORKDIR /app

COPY stellar-payment-platform/package*.json ./

COPY stellar-payment-platform/prisma ./prisma

RUN npm ci 

COPY stellar-payment-platform/ .

EXPOSE 5000
CMD ["node", "server.js"]